New rule: postMessage-no-wildcard-targets
Automattic/eslint-plugin-wpcalypso pull request #33
Opened 2017-01-26 07:14 UTC by dmsnell

Adds a new rule to warn when attempting to use the wildcard target
origin with `postMessage()`, which introduces a security vulnerability
allowing for data scraping by unintended parties.

For review I would especially appreciate some consideration for if I have used the right patterns here. Most of what I did was copy and paste work from other existing rules.

At first I wanted to limit this rule to invocations of `window.postMessage()` and `contentWindow.postMessage()` but then changed my mind because of the likelihood that someone might bind these and drop the parent object from the call, mixed with the unlikelihood that we would find the second parameter as the wildcard in these cases if they weren't actually calling `postMessage()` the way we expect.

2017-01-30 19:47 UTC, aduth commented
Tests failing on lint issues (whitespace consistency). There's one lint issue in an existing master file, but several more from this branch.

By convention, I think we should also stick to entirely lowercase rule names, either `postmessage-no-wildcard-targets` or `post-message-no-wildcard-targets`

2017-01-30 19:49 UTC, aduth commented
Fixed lint issue from master in a75ac9f1113a8fd1c9b6e65b87f47847b3d419a9.

2017-01-31 23:13 UTC, aduth commented on README.md
> +- [`post-message-no-wildcard-targets`](docs/rules/postMessage-no-wildcard-targets): Disallow using the wildcard '*' in `postMessage`
This is a broken link (needs `.md`)

2017-01-31 23:16 UTC, dmsnell commented on README.md
> +- [`post-message-no-wildcard-targets`](docs/rules/postMessage-no-wildcard-targets): Disallow using the wildcard '*' in `postMessage`
added the `.me` and updated the name

2017-01-31 23:33 UTC, aduth commented on tests/lib/rules/post-message-no-wildcard-targets.js
> +        { code: 'foo()' },
Hmm, why aren't these failing on mixed spacing? Lint might not be covering tests.

2017-01-31 23:36 UTC, aduth commented on tests/lib/rules/post-message-no-wildcard-targets.js
> +	invalid: [
Seems fine after testing it myself, but might be worth adding a test for real-world example where postMessage is called on a window object, e.g. `frame.postMessage( 'bob', '*' )`

2017-01-31 23:40 UTC, dmsnell commented on tests/lib/rules/post-message-no-wildcard-targets.js
> +        { code: 'foo()' },
oops. I didn't check after I used `elint --fix`

2017-01-31 23:43 UTC, dmsnell commented on tests/lib/rules/post-message-no-wildcard-targets.js
> +        { code: 'foo()' },
replaced with tabs in 9554013

2017-01-31 23:44 UTC, dmsnell commented on tests/lib/rules/post-message-no-wildcard-targets.js
> +	invalid: [
more tests added in ef586eb

2017-02-01 01:04 UTC, aduth approved these changes
LGTM 👍

2017-02-01 02:29 UTC, deBhal requested changes
Looks good overall!

I was looking at that `node.arguments.length < 2` check, and wondering what the right way to handle it was, so I went looking for some examples where we were calling postMessage with a single value, and I found this gem for you, which would be nice to catch:

`target.postMessage(JSON.stringify(msg), o.origin || '*');`

For the single argument case, it's nearly always going to be a convenience function, and hopefully we'll catch it in the underlying convenience function itself, so I think ignoring it is the appropriate response. 👍

2017-02-01 02:41 UTC, deBhal commented
Also, if you wanted to you could add `postMessage( '*', 'some.explicit.domain' )` to the "ok" list, just because that's the kind of implementation mistake that I might make.

2017-02-01 04:21 UTC, dmsnell commented
> target.postMessage(JSON.stringify(msg), o.origin || '*');

ooh. I don't like that usage. actually I know there are ways around this but I'm trying to make a reasoned judgment on how far we should go

```js
const domain = '*';
target.postMessage( 'message', domain );
```

2017-02-01 04:22 UTC, dmsnell commented
> Also, if you wanted to you could add postMessage( '*', 'some.explicit.domain' ) to the "ok" list, just because that's the kind of implementation mistake that I might make.

what do you mean by this @deBhal? just put it in the tests/examples to show that it's fine to send a message of `'*'`?

2017-02-01 21:28 UTC, deBhal commented
Yes and yes.

I also dislike that `||` a lot and would complain about it gleefully, which might be coloring my judgement :)

You're totally right that a line needs to be drawn somewhere, and there's no point trying to catch someone who's maliciously trying to avoid the rule, but someone _might_ do it innocently, and it's not too hard to check programmatically (similar to the [binary concatenation we do in i18n-calypso]( https://github.com/Automattic/i18n-calypso/blob/d56d4929bdc2606862f256660febcf6599e44252/cli/preprocess-xgettextjs-match.js#L79 )). It's a pretty subjective call, though, and I coming down on the "not checking" side seems justifiable if you want to do that.

( As an aside, I was idly wondering about a debug wrapper around postMessage to raise an error if '*' was ever used as the targetOrigin in `dev` through function/variable shenanigans, but that's really clearly out of scope for this PR. )

And yes, I was suggesting just adding the call to the `valid` list to document and verify that `'*'` is an acceptable message but not an acceptable `targetOrigin`, without making any other code changes.

2017-02-01 21:52 UTC, dmsnell commented
> I also dislike that || a lot and would complain about it gleefully

for what it's worth I didn't see any occurrences of this inside Calypso.

I think adding a debug wrapper for `postMessage` isn't a terrible idea so we could catch runtime `*`s, but hopefully this linter will be enough of a motivation for developers to not use it.

2017-02-01 23:15 UTC, merged